### ISSUE TITLE
_Arcade/_alternatives/_Rod-Land/R&T (Rod-Land Prototype).mra not filtered

### ISSUE THREAD

**Issue by loki666** [atrac17/Coin-Op_Collection#4]
_Arcade/_alternatives/_Rod-Land/R&T (Rod-Land Prototype).mra is not filtered with
filter = !alternatives

**Comment by atrac17** [comment]
Has nothing to do with the core.

**Comment by loki666** [comment]
who's talking about a core ?
I'll be more specific,

the tag "18", is missing in your db.json for the file "_Arcade/_alternatives/_Rod-Land/R&T (Rod-Land Prototype).mra"

**Comment by atrac17** [comment]
Those are auto generated. This is not something I maintain. I don't support AO.
